name: Tests

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:
    # Activate execution from another workflow

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run dev &

      - name: Wait for server to start
        run: sleep 10s

      - name: Run Cypress tests
        run: npm run cypress:run
